import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { ClerkProvider } from '@clerk/nextjs'

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "University News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className} bg-[#f3f4f6]`}>
          <div className="container">
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
